package com.blackjade.crm.apis.wallet;

public class WalletStatus {
public static final int CUSTOMER_GROUP_ID = 1 ;
	
	public static enum DepositEnum {
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
		PNSID_MSUT_MORE_THAN_ZERO,
		PNSGID_MSUT_MORE_THAN_ZERO,
		QUANTITY_MUST_BE_POSITIVE_NUMBER,
		FAILED,
		SUCCESS,
	}
	
	public static enum WithdrawEnum {
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
		PNSID_MSUT_MORE_THAN_ZERO,
		PNSGID_MSUT_MORE_THAN_ZERO,
		QUANTITY_MUST_BE_POSITIVE_NUMBER,
		RECEIVE_ADDRESS_IS_INVALID,
		FAILED,
		SUCCESS,
	}
	
	public static enum SaveCaccEnum {
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
		PNSID_MSUT_MORE_THAN_ZERO,
		PNSGID_MSUT_MORE_THAN_ZERO,
		FAILED,
		SUCCESS,
		THIS_TYPE_IS_ALREADY_EXITS
	}
	
	public static enum GetReceiveAddressEnum {
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
		PNSID_MUST_MORE_THAN_ZERO,
		PNSGID_MUST_MORE_THAN_ZERO,
		CLIENTID_MUST_MORE_THAN_ZERO,
		FAILED,
		SUCCESS
	}
}
