package com.blackjade.crm.apis.customer;

public class CustomerStatus {
	
	public static enum LoginEnum {
		SERVER_BUSY,
		REQUEST_ID_IS_EMPTY,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		MESSAGE_ID_IS_EMPTY,
		MESSAGE_ID_IS_INVALID,
		USERNAME_OR_EMAIL_IS_EMPTY,
		PASSWORD_IS_EMPTY,
		UNKOWN,
		USERNAME_OR_PASSWORD_WRONG,
		EMAIL_OR_PASSWORD_WRONG,
		FAILED,
		SUCCESS
	}
	
	
	public static enum RegisterEnum {
		EMAIL_IS_EMPTY,
		IDENTIFICATION_IS_EMPTY,
		MOBILE_IS_EMPTY,
		CONFIRM_PASSWORD_IS_EMPTY,
		PASSWORD_IS_EMPTY,
		USERNAME_IS_EMPTY,
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
		SERVER_BUSY,
		USERNAME_IS_EXISTS,
		EMAIL_IS_EXISTS,
		FAILED,
		SUCCESS
	}
	
	
	public static enum VerifyEmailEnum {
		SERVER_BUSY,
		TOKEN_IS_EMTPY,
		USERNAME_IS_EMTPY,
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
		DELETE_REDIS_KEY_FAILED,
		EMAIL_VERIFY_CODE_EXPIRE,
		EMIAL_VERIFY_CODE_MISMATCH,
		USERNAME_IS_NOT_EXITS,
		DATABASE_UPDATE_FAILED,
		FAILED,
		SUCCESS
	}
	
	public static enum ForgotPwEnum {
		EMAIL_IS_EMPTY,
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
		EMAIL_EXISTS,
		SERVER_BUSY,
		EMAIL_NOT_FOUND,
		FAILED,
		SUCCESS
	}
	
	public static enum ResetPwEnum {
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
		TOKEN_MISMATCH,
		TOKEN_EXPIRE,
		RESET_PASSWORD_FAILED,
		SERVER_BUSY,
		NEW_PASSWORD_MISMATCH_CONFIRM_PASSWORD,
		CONFIRM_PASSWORD_IS_EMPTY,
		NEW_PASSWORD_IS_EMPTY,
		TOKEN_IS_EMPTY,
		EMAIL_IS_EMPTY,
		FAILED,
		SUCCESS
	}
	
	public static enum ChangePwEnum {
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
	    SERVER_BUSY,
		OLDPW_IS_MISTAKE,
		OLDPW_NO_PERMIT_EQUAL_NEWPW,
		NEWPW_MISMATCH_REPW,
		REPW_IS_EMPTY,
		NEWPW_IS_EMPTY,
		OLDPW_IS_EMPTY,
		CLIENTID_IS_EMPTY,
		FAILED,
		SUCCESS
	}
	
	public static enum ModifyDetailsEnum {
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
		SERVER_BUSY,
		MODIFY_FAILED,
		CLIENTID_IS_EMPTY,
		FAILED,
		SUCCESS
	}
	
	public static enum SendVerifyEmailEnum {
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
		CLIENT_ID_IS_EMPTY,
		SEND_EMAIL_FAILED,
		SAVE_VERIFY_CODE_FAILED,
		NOT_FOUND_RECORD,
		SEVER_BUSY,
		FAILED,
		SUCCESS
	}
	
	public static enum ScanPersonalInfoEnum {
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
		CLIENT_ID_IS_EMPTY,
		NOT_FOUND_RECORD,
		SEVER_BUSY,
		FAILED,
		SUCCESS
	}
	
	public static enum CheckUsernameUniqueEnum {
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
		USERNAME_NOT_PERMIT_EMPTY,
		USERNAME_ALREADY_EXITS,
		FAILED,
		SUCCESS
	}
	
	public static enum CheckEmailUniqueEnum {
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
		EMAIL_NOT_PERMIT_EMPTY,
		EMAIL_ALREADY_EXITS,
		FAILED,
		SUCCESS
	}
	
	public static enum EmailAutoLoginEnum {
		DATABASE_UPDATE_FAILED,
		SERVER_BUSY,
		MESSAGE_ID_IS_INVALID,
		REQUEST_ID_LENGTH_MORE_THAN_36,
		REQUEST_ID_IS_EMPTY,
		USERNAME_NOT_PERMIT_EMPTY,
		TOKEN_NOT_PERMIT_EMPTY,
		TOKEN_IS_INVALID,
		FAILED,
		SUCCESS
	}
}
